version: '2'

services:
  kali:
    image:
      savmil/kali
    networks:
      mia:
        ipv4_address: 172.18.0.5
    privileged: true

  runipsec:
    image:
      savmil/ipsec
    networks:
      mia:
        ipv4_address: 172.18.0.2
      mia1:
        ipv4_address: 173.18.0.2      
#mia2:
      #  ipv4_address: 10.18.0.1
    expose:
      - "500/udp"
      - "4500/udp"
    volumes:
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
    privileged: true

  ipseclient:
    image:
      savmil/ipsecclient
    networks:
      mia:
        ipv4_address: 172.18.0.3
     #mia1:
      #  ipv4_address: 173.18.0.3
    volumes:
      - /lib/modules:/lib/modules
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true

  wireshark:
    image:
      #stealthandsecure-master-688752154bfe46775c9d1ea5cb0ef3edca323d72_wireshark_1
      #nsunina/wireshark
      savmil/wireshark
    networks:
      mia:
        ipv4_address: 172.18.0.4
      #mia1:
      #  ipv4_address: 173.18.0.4
    stdin_open: true
    tty: true
    #expose:
    #  - "500/udp"
    ports:
      - '14500:14500'
    #  - '500:500/udp'
    environment:
      - XPRA_PW=wireshark
    cap_add:
      - NET_ADMIN
    privileged: true
    #command: bash -c "sudo iptables-restore < /etc/iptables/rules.v4 && ping 172.18.0.4 >>/dev/null"

networks:
  mia:
    #driver: bridge
    ipam:
      #driver: bridge
      config:
        - subnet: 172.18.0.0/24
  mia1:
    #driver: bridge
    ipam:
      #driver: bridge
      config:
        - subnet: 173.18.0.0/24
#  mia2:
#    ipam:
#      config:
#        - subnet: 10.18.0.0/24 
